# Generated by Django 4.2 on 2023-04-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='motosicleta')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'moto',
                'verbose_name_plural': 'motos',
            },
        ),
    ]
