# Generated by Django 4.2 on 2023-04-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motos',
            new_name='Galeria',
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'galeria', 'verbose_name_plural': 'galerias'},
        ),
    ]
