# Generated by Django 4.2 on 2023-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_rename_motos_galeria_alter_galeria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
